const axios = require('axios');
const accountConnectorService = require('./accountConnectorService');
const API_URL = 'https://api.intercom.io';
const clamp = (value, fallback, minimum, maximum) => { const parsed = Number.parseInt(value, 10); return Number.isFinite(parsed) ? Math.max(minimum, Math.min(maximum, parsed)) : fallback; };
const compact = value => Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined && item !== null && item !== ''));
const boundedText = value => { const text = String(value || '').replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi, '[redacted email]').replace(/\bhttps?:\/\/\S+/gi, '[redacted url]').replace(/\s+/g, ' ').trim(); return text ? text.slice(0, 160) : undefined; };
const validId = value => typeof value === 'string' && value.length > 0 && value.length <= 2048 && /^[A-Za-z0-9._~+/=-]+$/.test(value);
const unixDate = value => { if (value === undefined || value === null || value === '') return null; if (!/^\d{1,12}$/.test(String(value))) return null; const date = new Date(Number(value) * 1000); return Number.isNaN(date.getTime()) ? null : date; };
const invalidResponse = message => { const error = new Error(message); error.statusCode = 502; return error; };
const conversation = value => { const createdAt = unixDate(value?.created_at); const updatedAt = unixDate(value?.updated_at); if (!validId(String(value?.id || '')) || (value?.created_at && !createdAt) || (value?.updated_at && !updatedAt)) return null; return compact({ id: `conversation:${value.id}`, sourceType: 'conversation', conversationId: String(value.id), name: boundedText(value.title) || 'Intercom conversation', status: ['open', 'closed', 'snoozed'].includes(value.state) ? value.state : 'open', createdAt: createdAt?.toISOString(), updatedAt: updatedAt?.toISOString() }); };
class IntercomWorkSignalClient {
  constructor(options = {}) { this.http = options.http || axios; this.accountConnectorService = options.accountConnectorService || accountConnectorService; }
  getConfig() { return { timeout: clamp(process.env.SNEUP_INTERCOM_TIMEOUT_MS, 15000, 1000, 60000), maxConversations: clamp(process.env.SNEUP_INTERCOM_MAX_CONVERSATIONS, 500, 1, 5000), pageSize: clamp(process.env.SNEUP_INTERCOM_PAGE_SIZE, 100, 1, 150) }; }
  getAccessToken(account) { const credentials = this.accountConnectorService.getAccountCredentials(account); const token = credentials.accessToken || credentials.token; if (!token) { const error = new Error('Intercom OAuth access token is missing. Reconnect this account to continue syncing.'); error.statusCode = 503; throw error; } return token; }
  async fetchDelta(account, cursor) { const cursorDate = cursor ? new Date(cursor) : null; if (cursor && Number.isNaN(cursorDate.getTime())) { const error = new Error('Intercom work-signal cursor is invalid. Reconnect this account to establish a new cursor.'); error.statusCode = 400; throw error; } const config = this.getConfig(); const token = this.getAccessToken(account); const records = []; const seenTokens = new Set(); let startingAfter; let newest = cursorDate; let pages = 0;
    do { const remaining = config.maxConversations - records.length; if (remaining <= 0) { const error = new Error('Intercom sync reached its configured conversation limit. Increase SNEUP_INTERCOM_MAX_CONVERSATIONS before continuing.'); error.statusCode = 413; throw error; } const response = await this.http.get(`${API_URL}/conversations`, { params: { per_page: Math.min(config.pageSize, remaining), ...(startingAfter ? { starting_after: startingAfter } : {}) }, headers: { Accept: 'application/json', Authorization: `Bearer ${token}`, 'Intercom-Version': '2.15', 'User-Agent': 'Sneup Digital Project Manager (support@noodzakelijk.online)' }, timeout: config.timeout, maxRedirects: 0, proxy: false }); const values = response?.data?.conversations; const total = Number(response?.data?.total_count); if (!Array.isArray(values) || (Number.isFinite(total) && total > config.maxConversations) || values.length > remaining) throw invalidResponse('Intercom returned an invalid conversation-metadata page. Reconnect this account before syncing again.'); const normalized = values.map(conversation).filter(Boolean); if (normalized.length !== values.length) throw invalidResponse('Intercom returned invalid conversation metadata. Reconnect this account before syncing again.'); normalized.forEach(item => { const updatedAt = new Date(item.updatedAt || item.createdAt); if (!Number.isNaN(updatedAt.getTime()) && (!newest || updatedAt > newest)) newest = updatedAt; if (!cursorDate || Number.isNaN(updatedAt.getTime()) || updatedAt >= cursorDate) records.push(item); }); const next = response?.data?.pages?.next?.starting_after; if (next && (!validId(next) || seenTokens.has(next) || values.length >= remaining)) { const error = new Error('Intercom conversation pagination cannot continue safely. Reconnect this account before syncing again.'); error.statusCode = next && values.length >= remaining ? 413 : 502; throw error; } if (next) seenTokens.add(next); startingAfter = next || null; pages += 1; } while (startingAfter);
    return { records, nextCursor: newest ? newest.toISOString() : cursor || null, hasMore: false, metadata: { source: 'intercom_conversation_list_metadata', conversations: records.length, pages, contentPolicy: 'conversation_list_metadata_only_no_bodies_parts_contacts_companies_teammates_tags_urls_attachments_raw_payloads_or_provider_writes' } };
  }
}
const intercomWorkSignalClient = new IntercomWorkSignalClient();
module.exports = intercomWorkSignalClient;
module.exports.IntercomWorkSignalClient = IntercomWorkSignalClient;
