const axios = require('axios');
const net = require('net');
const accountConnectorService = require('./accountConnectorService');
const clamp = (value, fallback, minimum, maximum) => { const parsed = Number.parseInt(value, 10); return Number.isFinite(parsed) ? Math.max(minimum, Math.min(maximum, parsed)) : fallback; };
const compact = value => Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined && item !== null && item !== ''));
const boundedText = value => { const text = String(value || '').replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi, '[redacted email]').replace(/\bhttps?:\/\/\S+/gi, '[redacted url]').replace(/\s+/g, ' ').trim(); return text ? text.slice(0, 160) : undefined; };
const isPrivateIpv4 = hostname => { const parts = hostname.split('.').map(Number); return parts.length === 4 && parts.every(part => Number.isInteger(part) && part >= 0 && part <= 255) && (parts[0] === 0 || parts[0] === 10 || parts[0] === 127 || (parts[0] === 169 && parts[1] === 254) || (parts[0] === 172 && parts[1] >= 16 && parts[1] <= 31) || (parts[0] === 192 && parts[1] === 168)); };
const validId = value => /^[A-Za-z0-9_-]{1,128}$/.test(String(value || ''));
const parseDate = value => { if (!value) return null; const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; };
const invalidResponse = message => { const error = new Error(message); error.statusCode = 502; return error; };
const team = value => validId(value?.id) ? compact({ id: `team:${value.id}`, sourceType: 'team', teamId: String(value.id), name: boundedText(value.display_name) || 'Mattermost team', status: 'open' }) : null;
class MattermostWorkSignalClient {
  constructor(options = {}) { this.http = options.http || axios; this.accountConnectorService = options.accountConnectorService || accountConnectorService; }
  getApiUrl(account) { const raw = String(account?.metadata?.fields?.baseUrl || '').trim(); let url; try { url = new URL(raw); } catch { url = null; } const hostname = url?.hostname?.toLowerCase() || ''; if (!url || url.protocol !== 'https:' || url.username || url.password || url.port || url.search || url.hash || !hostname || hostname === 'localhost' || hostname.endsWith('.localhost') || hostname.endsWith('.local') || net.isIP(hostname) === 6 || isPrivateIpv4(hostname)) { const error = new Error('Mattermost instance URL must be a public HTTPS URL without credentials or a custom port.'); error.statusCode = 400; throw error; } return url.toString().replace(/\/$/, ''); }
  getConfig(account) { return { apiUrl: this.getApiUrl(account), timeout: clamp(process.env.SNEUP_MATTERMOST_TIMEOUT_MS, 15000, 1000, 60000), maxTeams: clamp(process.env.SNEUP_MATTERMOST_MAX_TEAMS, 100, 1, 500), pageSize: clamp(process.env.SNEUP_MATTERMOST_PAGE_SIZE, 60, 1, 200) }; }
  getToken(account) { const credentials = this.accountConnectorService.getAccountCredentials(account); const token = credentials.token || credentials.accessToken || credentials.apiKey; if (!token) { const error = new Error('Mattermost personal access token is missing. Reconnect this account to continue syncing.'); error.statusCode = 503; throw error; } return token; }
  async fetchDelta(account, cursor) { const cursorDate = cursor ? parseDate(cursor) : null; if (cursor && !cursorDate) { const error = new Error('Mattermost work-signal cursor is invalid. Reconnect this account to establish a new cursor.'); error.statusCode = 400; throw error; } const config = this.getConfig(account); const token = this.getToken(account); const records = []; let page = 0; let pages = 0; while (true) { const remaining = config.maxTeams - records.length; if (remaining <= 0) { const error = new Error('Mattermost sync reached its configured team limit. Increase SNEUP_MATTERMOST_MAX_TEAMS before continuing.'); error.statusCode = 413; throw error; } const perPage = Math.min(config.pageSize, remaining); const response = await this.http.get(`${config.apiUrl}/api/v4/users/me/teams`, { params: { page, per_page: perPage }, headers: { Accept: 'application/json', Authorization: `Bearer ${token}`, 'User-Agent': 'Sneup Digital Project Manager (support@noodzakelijk.online)' }, timeout: config.timeout, maxRedirects: 0, proxy: false }); const values = response?.data; if (!Array.isArray(values) || values.length > perPage) throw invalidResponse('Mattermost returned an invalid team-metadata page. Reconnect this account before syncing again.'); const normalized = values.map(team).filter(Boolean); if (normalized.length !== values.length) throw invalidResponse('Mattermost returned an invalid team identifier. Reconnect this account before syncing again.'); records.push(...normalized); pages += 1; if (values.length < perPage) break; if (records.length >= config.maxTeams) { const error = new Error('Mattermost sync reached its configured team limit before the provider collection ended. Increase SNEUP_MATTERMOST_MAX_TEAMS before continuing.'); error.statusCode = 413; throw error; } page += 1; }
    return { records, nextCursor: cursorDate ? cursorDate.toISOString() : null, hasMore: false, metadata: { source: 'mattermost_current_user_team_metadata', teams: records.length, pages, contentPolicy: 'current_user_team_metadata_only_no_channels_posts_threads_direct_messages_users_roles_permissions_invites_files_reactions_preferences_server_configuration_raw_payloads_or_provider_writes' } }; }
}
const mattermostWorkSignalClient = new MattermostWorkSignalClient();
module.exports = mattermostWorkSignalClient;
module.exports.MattermostWorkSignalClient = MattermostWorkSignalClient;
