const axios = require('axios');
const accountConnectorService = require('./accountConnectorService');
const API_URL = 'https://api.podio.com';
const clamp = (value, fallback, minimum, maximum) => { const parsed = Number.parseInt(value, 10); return Number.isFinite(parsed) ? Math.max(minimum, Math.min(maximum, parsed)) : fallback; };
const compact = value => Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined && item !== null && item !== ''));
const boundedText = value => { const text = String(value || '').replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi, '[redacted email]').replace(/\bhttps?:\/\/\S+/gi, '[redacted url]').replace(/\s+/g, ' ').trim(); return text ? text.slice(0, 160) : undefined; };
const validId = value => /^\d{1,18}$/.test(String(value || ''));
const parseDate = value => { if (!value) return null; const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; };
const invalidResponse = message => { const error = new Error(message); error.statusCode = 502; return error; };
const item = value => { const createdAt = parseDate(value?.initial_revision?.created_on); const updatedAt = parseDate(value?.current_revision?.created_on || value?.last_event_on); if (!validId(value?.item_id) || (value?.initial_revision?.created_on && !createdAt) || ((value?.current_revision?.created_on || value?.last_event_on) && !updatedAt)) return null; return compact({ id: `item:${value.item_id}`, sourceType: 'item', itemId: String(value.item_id), name: boundedText(value.title) || `Podio item ${value.item_id}`, status: value?.current_revision?.type === 'delete' ? 'archived' : 'open', createdAt: createdAt?.toISOString(), updatedAt: updatedAt?.toISOString() }); };
class PodioWorkSignalClient {
  constructor(options = {}) { this.http = options.http || axios; this.accountConnectorService = options.accountConnectorService || accountConnectorService; }
  getConfig() { return { timeout: clamp(process.env.SNEUP_PODIO_TIMEOUT_MS, 15000, 1000, 60000), maxItems: clamp(process.env.SNEUP_PODIO_MAX_ITEMS, 1000, 1, 5000), pageSize: clamp(process.env.SNEUP_PODIO_PAGE_SIZE, 100, 1, 1000) }; }
  getCredentials(account) { const credentials = this.accountConnectorService.getAccountCredentials(account); const appId = String(account?.metadata?.fields?.appId || '').trim(); const appToken = credentials.appToken; if (!validId(appId) || !appToken) { const error = new Error('Podio app ID and app token are required. Reconnect this account with the one app Sneup may read.'); error.statusCode = 503; throw error; } return { appId, appToken }; }
  async getAccessToken(credentials, config) { const response = await this.http.post(`${API_URL}/oauth/token/v2`, { grant_type: 'app', app_id: Number(credentials.appId), app_token: credentials.appToken }, { headers: { Accept: 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'Sneup Digital Project Manager (support@noodzakelijk.online)' }, timeout: config.timeout, maxRedirects: 0, proxy: false }); const token = response?.data?.access_token; if (typeof token !== 'string' || token.length < 16 || token.length > 4096) throw invalidResponse('Podio app authentication returned an invalid access token. Reconnect this account before syncing again.'); return token; }
  async fetchDelta(account, cursor) { const cursorDate = cursor ? parseDate(cursor) : null; if (cursor && !cursorDate) { const error = new Error('Podio work-signal cursor is invalid. Reconnect this account to establish a new cursor.'); error.statusCode = 400; throw error; } const config = this.getConfig(); const credentials = this.getCredentials(account); const token = await this.getAccessToken(credentials, config); const records = []; let newest = cursorDate; let offset = 0; let pages = 0; let total;
    do { const response = await this.http.get(`${API_URL}/item/app/${encodeURIComponent(credentials.appId)}/`, { params: { limit: Math.min(config.pageSize, config.maxItems - offset), offset, sort_by: 'created_on', sort_desc: true }, headers: { Accept: 'application/json', Authorization: `OAuth2 ${token}`, 'User-Agent': 'Sneup Digital Project Manager (support@noodzakelijk.online)' }, timeout: config.timeout, maxRedirects: 0, proxy: false }); const values = response?.data?.items; total = Number(response?.data?.total); if (!Array.isArray(values) || !Number.isFinite(total) || total < 0 || values.length > config.maxItems - offset) throw invalidResponse('Podio returned an invalid item-metadata page. Reconnect this account before syncing again.'); if (total > config.maxItems) { const error = new Error('Podio app item count exceeds SNEUP_PODIO_MAX_ITEMS. Increase that limit before continuing.'); error.statusCode = 413; throw error; } const normalized = values.map(item).filter(Boolean); if (normalized.length !== values.length) throw invalidResponse('Podio returned invalid item metadata. Reconnect this account before syncing again.'); normalized.forEach(record => { const updatedAt = parseDate(record.updatedAt || record.createdAt); if (updatedAt && (!newest || updatedAt > newest)) newest = updatedAt; if (!cursorDate || !updatedAt || updatedAt >= cursorDate) records.push(record); }); offset += values.length; pages += 1; if (values.length === 0 && offset < total) throw invalidResponse('Podio returned an unsafe item pagination sequence. Reconnect this account before syncing again.'); } while (offset < total);
    return { records, nextCursor: newest ? newest.toISOString() : cursor || null, hasMore: false, metadata: { source: 'podio_app_item_metadata', items: records.length, pages, contentPolicy: 'single_app_item_metadata_only_no_field_values_comments_files_people_urls_tags_raw_payloads_or_provider_writes' } };
  }
}
const podioWorkSignalClient = new PodioWorkSignalClient();
module.exports = podioWorkSignalClient;
module.exports.PodioWorkSignalClient = PodioWorkSignalClient;
