const axios = require('axios');
const accountConnectorService = require('./accountConnectorService');
const API_URL = 'https://webexapis.com/v1';
const clamp = (value, fallback, minimum, maximum) => { const parsed = Number.parseInt(value, 10); return Number.isFinite(parsed) ? Math.max(minimum, Math.min(maximum, parsed)) : fallback; };
const compact = value => Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined && item !== null && item !== ''));
const boundedText = value => { const text = String(value || '').replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi, '[redacted email]').replace(/\bhttps?:\/\/\S+/gi, '[redacted url]').replace(/\s+/g, ' ').trim(); return text ? text.slice(0, 160) : undefined; };
const validId = value => typeof value === 'string' && value.length > 0 && value.length <= 2048 && /^[A-Za-z0-9._~+/=-]+$/.test(value);
const parseDate = value => { if (!value) return null; const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; };
const invalidResponse = message => { const error = new Error(message); error.statusCode = 502; return error; };
const meeting = value => { const id = String(value?.id || ''); const startAt = parseDate(value?.start); const endAt = parseDate(value?.end); const createdAt = parseDate(value?.created); const updatedAt = parseDate(value?.lastActivity || value?.modified); if (!validId(id) || (value?.start && !startAt) || (value?.end && !endAt) || (value?.created && !createdAt) || ((value?.lastActivity || value?.modified) && !updatedAt)) return null; return compact({ id: `meeting:${id}`, sourceType: 'meeting', meetingId: id, name: boundedText(value.title) || 'Webex meeting', status: ['scheduled', 'ready', 'inProgress', 'ended', 'expired', 'missed'].includes(value.state) ? value.state : 'scheduled', meetingType: ['meetingSeries', 'scheduledMeeting', 'meeting'].includes(value.meetingType) ? value.meetingType : undefined, startAt: startAt?.toISOString(), endAt: endAt?.toISOString(), createdAt: createdAt?.toISOString(), updatedAt: updatedAt?.toISOString() }); };
class WebexWorkSignalClient {
  constructor(options = {}) { this.http = options.http || axios; this.accountConnectorService = options.accountConnectorService || accountConnectorService; this.now = options.now || (() => new Date()); }
  getConfig() { return { timeout: clamp(process.env.SNEUP_WEBEX_TIMEOUT_MS, 15000, 1000, 60000), maxMeetings: clamp(process.env.SNEUP_WEBEX_MAX_MEETINGS, 500, 1, 1000), pageSize: clamp(process.env.SNEUP_WEBEX_PAGE_SIZE, 100, 1, 1000), initialLookbackDays: clamp(process.env.SNEUP_WEBEX_INITIAL_LOOKBACK_DAYS, 30, 1, 365), futureHorizonDays: clamp(process.env.SNEUP_WEBEX_FUTURE_HORIZON_DAYS, 120, 1, 365) }; }
  getAccessToken(account) { const credentials = this.accountConnectorService.getAccountCredentials(account); const token = credentials.accessToken || credentials.token; if (!token) { const error = new Error('Webex access token is missing. Reconnect this account with meeting:schedules_read to continue syncing.'); error.statusCode = 503; throw error; } return token; }
  async fetchDelta(account, cursor) { const config = this.getConfig(); const token = this.getAccessToken(account); const cursorDate = cursor ? parseDate(cursor) : null; if (cursor && !cursorDate) { const error = new Error('Webex work-signal cursor is invalid. Reconnect this account to establish a new cursor.'); error.statusCode = 400; throw error; } const now = this.now(); const from = cursorDate || new Date(now.getTime() - config.initialLookbackDays * 86400000); const to = new Date(now.getTime() + config.futureHorizonDays * 86400000); const pageSize = Math.min(config.pageSize, config.maxMeetings); const response = await this.http.get(`${API_URL}/meetings`, { params: { from: from.toISOString(), to: to.toISOString(), max: pageSize }, headers: { Accept: 'application/json', Authorization: `Bearer ${token}`, 'User-Agent': 'Sneup Digital Project Manager (support@noodzakelijk.online)' }, timeout: config.timeout, maxRedirects: 0, proxy: false }); const values = response?.data?.items; if (!Array.isArray(values) || values.length > pageSize) throw invalidResponse('Webex returned an invalid meeting-metadata collection. Reconnect this account before syncing again.'); if (values.length === pageSize) { const error = new Error('Webex meeting metadata reached its configured page limit. Increase SNEUP_WEBEX_PAGE_SIZE and SNEUP_WEBEX_MAX_MEETINGS before continuing.'); error.statusCode = 413; throw error; } const normalized = values.map(meeting).filter(Boolean); if (normalized.length !== values.length) throw invalidResponse('Webex returned invalid meeting metadata. Reconnect this account before syncing again.'); let newest = cursorDate; normalized.forEach(item => { const updatedAt = parseDate(item.updatedAt || item.createdAt || item.startAt); if (updatedAt && (!newest || updatedAt > newest)) newest = updatedAt; }); return { records: normalized.filter(item => { const updatedAt = parseDate(item.updatedAt || item.createdAt || item.startAt); return !cursorDate || !updatedAt || updatedAt >= cursorDate; }), nextCursor: newest ? newest.toISOString() : cursor || null, hasMore: false, metadata: { source: 'webex_meeting_list_metadata', meetings: normalized.length, pages: 1, from: from.toISOString(), to: to.toISOString(), contentPolicy: 'meeting_list_metadata_only_no_agendas_passwords_hosts_invitees_join_links_recordings_transcripts_messages_spaces_people_raw_payloads_or_provider_writes' } }; }
}
const webexWorkSignalClient = new WebexWorkSignalClient();
module.exports = webexWorkSignalClient;
module.exports.WebexWorkSignalClient = WebexWorkSignalClient;
