const axios = require('axios');
const accountConnectorService = require('./accountConnectorService');
const API_URL = 'https://projectsapi.zoho.com/restapi';
const clamp = (value, fallback, minimum, maximum) => { const parsed = Number.parseInt(value, 10); return Number.isFinite(parsed) ? Math.max(minimum, Math.min(maximum, parsed)) : fallback; };
const compact = value => Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined && item !== null && item !== ''));
const validId = value => /^[1-9][0-9]{0,23}$/.test(String(value || ''));
const boundedText = value => { const text = String(value || '').replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi, '[redacted email]').replace(/\bhttps?:\/\/\S+/gi, '[redacted url]').replace(/\s+/g, ' ').trim(); return text ? text.slice(0, 160) : undefined; };
const parseDate = value => { if (!value) return null; const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; };
const invalidResponse = message => { const error = new Error(message); error.statusCode = 502; return error; };
const project = value => { const projectId = String(value?.id || ''); const percent = value?.project_percent; const parsedPercent = percent === undefined || percent === null || percent === '' ? undefined : Number(percent); const startAt = parseDate(value?.start_date_long); const endAt = parseDate(value?.end_date_long); const updatedAt = parseDate(value?.updated_date_long); if (!validId(projectId) || !boundedText(value?.name) || String(value?.status || '').toLowerCase() !== 'active' || (percent !== undefined && (!Number.isFinite(parsedPercent) || parsedPercent < 0 || parsedPercent > 100)) || (value?.start_date_long && !startAt) || (value?.end_date_long && !endAt) || (value?.updated_date_long && !updatedAt)) return null; return compact({ id: `project:${projectId}`, sourceType: 'project', projectId, name: boundedText(value.name), status: 'active', percentComplete: parsedPercent, startAt: startAt?.toISOString(), endAt: endAt?.toISOString(), updatedAt: updatedAt?.toISOString() }); };
class ZohoProjectsWorkSignalClient {
  constructor(options = {}) { this.http = options.http || axios; this.accountConnectorService = options.accountConnectorService || accountConnectorService; }
  getConfig(account) { const portalId = String(account?.metadata?.fields?.portalId || '').trim(); if (!validId(portalId)) { const error = new Error('Zoho Projects portal ID must be a positive numeric identifier.'); error.statusCode = 400; throw error; } return { portalId, timeout: clamp(process.env.SNEUP_ZOHO_PROJECTS_TIMEOUT_MS, 15000, 1000, 60000), maxProjects: clamp(process.env.SNEUP_ZOHO_PROJECTS_MAX_PROJECTS, 250, 1, 1000), pageSize: clamp(process.env.SNEUP_ZOHO_PROJECTS_PAGE_SIZE, 100, 1, 200) }; }
  getToken(account) { const credentials = this.accountConnectorService.getAccountCredentials(account); const token = credentials.token || credentials.accessToken || credentials.apiKey; if (!token) { const error = new Error('Zoho Projects OAuth access token is missing. Reconnect this account to continue syncing.'); error.statusCode = 503; throw error; } return token; }
  async fetchDelta(account, cursor) { const cursorDate = cursor ? parseDate(cursor) : null; if (cursor && !cursorDate) { const error = new Error('Zoho Projects work-signal cursor is invalid. Reconnect this account to establish a new cursor.'); error.statusCode = 400; throw error; } const config = this.getConfig(account); const token = this.getToken(account); const records = []; let index = 1; let pages = 0; let scanned = 0; while (true) { const remaining = config.maxProjects - scanned; if (remaining <= 0) { const error = new Error('Zoho Projects sync reached its configured project limit. Increase SNEUP_ZOHO_PROJECTS_MAX_PROJECTS before continuing.'); error.statusCode = 413; throw error; } const range = Math.min(config.pageSize, remaining); const response = await this.http.get(`${API_URL}/portal/${config.portalId}/projects/`, { params: { status: 'active', index, range, sort_column: 'last_modified_time', sort_order: 'descending' }, headers: { Accept: 'application/json', Authorization: `Zoho-oauthtoken ${token}`, 'User-Agent': 'Sneup Digital Project Manager (support@noodzakelijk.online)' }, timeout: config.timeout, maxRedirects: 0, proxy: false }); const values = response?.data?.projects; if (!Array.isArray(values) || values.length > range) throw invalidResponse('Zoho Projects returned an invalid active-project page. Reconnect this account before syncing again.'); const normalized = values.map(project); if (normalized.some(item => !item)) throw invalidResponse('Zoho Projects returned invalid active-project metadata. Reconnect this account before syncing again.'); scanned += values.length; records.push(...normalized.filter(item => { const updatedAt = parseDate(item.updatedAt); return !cursorDate || !updatedAt || updatedAt >= cursorDate; })); pages += 1; if (values.length < range) break; if (scanned >= config.maxProjects) { const error = new Error('Zoho Projects sync reached its configured project limit before the provider collection ended. Increase SNEUP_ZOHO_PROJECTS_MAX_PROJECTS before continuing.'); error.statusCode = 413; throw error; } index += values.length; } const newest = records.reduce((latest, record) => { const date = parseDate(record.updatedAt); return date && (!latest || date > latest) ? date : latest; }, cursorDate); return { records, nextCursor: newest ? newest.toISOString() : cursor || null, hasMore: false, metadata: { source: 'zoho_projects_active_project_metadata', projects: records.length, pages, contentPolicy: 'active_project_metadata_only_no_milestones_tasks_issues_timesheets_documents_people_owners_descriptions_custom_fields_links_raw_payloads_or_provider_writes' } }; }
}
const zohoProjectsWorkSignalClient = new ZohoProjectsWorkSignalClient();
module.exports = zohoProjectsWorkSignalClient;
module.exports.ZohoProjectsWorkSignalClient = ZohoProjectsWorkSignalClient;
